### ISSUE TITLE
Wheel's Direction of Travel Inconsistent

### ISSUE THREAD

**Issue by CierraO** [Team2168/2020_SwerveBot#11]
ONLY with the internal encoder initialization code (currently commented out).

Depending on what position the azimuth is placed in upon startup, the direction of travel of the drivewheel will change.

**Comment by jcorcoran** [comment]
@CierraO , this is no longer a problem in recent branches right?

**Comment by CierraO** [comment]
@jcorcoran I haven't observed this issue, no
